### ISSUE TITLE
Time intervals of messages are not equally separated for fixed sample rate.

### ISSUE THREAD

**Issue by Yunusbcr** [facebookresearch/labgraph#19]
## ❓ Questions and Help

Timestamps of messages are not equally separated for fixed sample rate. How can I have equal time separation between samples?

## To Reproduce

In **simple_viz.py** change line 49 as,
```    
async def generate_noise(self) -> lg.AsyncPublisher:
        tmp = 0
        while True:
            now = time.time()
            print((now - tmp)*1000)
            tmp = now
            yield self.OUTPUT, RandomMessage(
                timestamp=now, data=np.random.rand(self.config.num_features)
            )
            await asyncio.sleep(1 / self.config.sample_rate)
```
and with `SAMPLE_RATE = 10.0` I am getting this time intervals(in ms) as output,

```
1634770261291.764
101.32384300231934
102.19454765319824
102.87952423095703
102.3719310760498
101.06134414672852
103.06859016418457
102.8130054473877
104.36487197875977
102.22911834716797
101.91011428833008
102.6158332824707
103.40309143066406
102.59652137756348
...
...
```
How can I have 100.0 ms time interval between samples?

P.S. For low sampling rate it is not a big deal but for high frequency sensors it becomes important.

**Comment by jfResearchEng** [comment]
Thanks for your question! This would be an expected behavior when using multiprocessing asynchronous streaming framework.

**Comment by jfResearchEng** [comment]
I'm going to close this issue for now. Feel free to reopen when you have more questions.
