### ISSUE TITLE
Linking issues on Ubuntu 20 for cthulhu

### ISSUE THREAD

**Issue by patrickmineault** [facebookresearch/labgraph#2]
## 🐛 Bug

`import cthulhubindings` fails with error` ImportError: cthulhubindings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: shm_unlink`

## To Reproduce

1. Installed labgraph on Ubuntu 20, with base install of Python 3.6 (from `ppa:deadsnakes/ppa`)
1. python3.6 -m labgraph.examples.simple_viz
1. `ImportError: /usr/local/lib/python3.6/dist-packages/labgraph-1.0.0-py3.6-linux-x86_64.egg/cthulhubindings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: shm_unlink`

The test suite also fails (all errors) as `import cthulhubindings` fails

## Expected behavior

*works*

## Environment

```
 - LabGraph Version (e.g., 1.0): 1.0.0
 - OS (e.g., Linux/Mac/Windows): Ubuntu 20.04.2 LTS
 - Python version: 3.6.14 from `ppa:deadsnakes/ppa`
 - Any other relevant information: N/A
```

## Additional context

It looks like the issue is in linking the relevant realtime libraries. I see in the buck config `-lrt` used in `exported_linker_flags`, but it doesn't look like it's picking it up. Is there a way to increase the verbosity of the buck outputs to be able to see the flags it passes to g++? I looked through the buck logs but nothing jumped out.

**Comment by jfResearchEng** [comment]
Thanks, Patrick, for reporting this issue. Pypi currently does not support Ubuntu. One alternative is to try to use another system. In the meanwhile, a cross-platform Pypi solution will be explored. We will keep you updated.

**Comment by patrickmineault** [comment]
I agree it would be convenient to install from PyPI. I'm building from source though, cloning from the git repo and compiling using buck version 577c273d9746e42769e5dbb7bb5a092ba3ec82c2.

**Comment by griffinmilsap** [comment]
Also curious - what is the fundamental limitation keeping this from running on python versions other than 3.6?  If it's the cthulhu bindings, I'd be quite eager for a pure-python fork of this project with Cthulhu stripped out.  It's an incredibly performant messaging library, but I get the feeling that a ZMQ backend would be more than sufficient for 90% of users.

**Comment by jfResearchEng** [comment]
Thank you, patrickmineault and patrickmineault for your feedback! We have included this issue in the todo list of LabGraph. Alternatively, a potential easy fix could be by switching to clang++.

**Comment by jfResearchEng** [comment]
Hi patrickmineault, the recent update could help address your Ubuntu-related issue. You could either run Dockerfile.Ubuntu or follow the instructions in the Dockerfile. I'm going to create some instructions on running Dockerfile shortly. Feel free to come back to this issue again should you encounter further issues using LabGraph. Thank you for helping us create the 1st issue in LabGraph!

**Comment by jfResearchEng** [comment]
Hi griffinmilsap, I will create an FAQ session containing this topic and hope you could come back and help us discuss more on this topic.

**Comment by jfResearchEng** [comment]
I'm going to close this issue for now. If have more questions, feel free to reopen this issue or create a new issue.

**Comment by pperanich** [comment]
Are there any further instructions on how to correct the above issue when compiling from source on Ubuntu 18 / 20?

Referenced issue:
`ImportError: /usr/local/lib/python3.6/dist-packages/labgraph-1.0.0-py3.6-linux-x86_64.egg/cthulhubindings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: shm_unlink`

**Comment by jfResearchEng** [comment]
An example on usage in Ubuntu can be found here: https://github.com/facebookresearch/labgraph/blob/main/Dockerfile.Ubuntu

**Comment by jfResearchEng** [comment]
> Are there any further instructions on how to correct the above issue when compiling from source on Ubuntu 18 / 20?
> 
> Referenced issue: `ImportError: /usr/local/lib/python3.6/dist-packages/labgraph-1.0.0-py3.6-linux-x86_64.egg/cthulhubindings.cpython-36m-x86_64-linux-gnu.so: undefined symbol: shm_unlink`

An example on usage in Ubuntu can be found here: https://github.com/facebookresearch/labgraph/blob/main/Dockerfile.Ubuntu

**Comment by pperanich** [comment]
I am attempting to build from source (with python3.9) rather than installing the PyPi package. After running `python3 setup.py install` within my conda env, it appears that everything is built correctly and installed, but upon importing into python, I get the following error:
```
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import labgraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/__init__.py", line 56, in <module>
    from .events import (
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/events/__init__.py", line 17, in <module>
    from .event_generator import (
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/events/event_generator.py", line 9, in <module>
    from ..graphs.topic import Topic
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/graphs/__init__.py", line 24, in <module>
    from .config import Config
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/graphs/config.py", line 8, in <module>
    from ..messages.message import Field, Message
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/messages/__init__.py", line 18, in <module>
    from .message import Message, TimestampedMessage
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/messages/message.py", line 15, in <module>
    from .._cthulhu.bindings import (
  File "/home/peranpl1/Documents/repos/labgraph/labgraph/_cthulhu/bindings.py", line 24, in <module>
    import cthulhubindings  # noqa: E402
ImportError: /home/peranpl1/miniconda/envs/lg-3.9/lib/python3.9/site-packages/cthulhubindings.cpython-39-x86_64-linux-gnu.so: undefined symbol: shm_unlink
```

The Dockerfile you linked is installing from PyPI rather than building from source.

Thanks for the help!

**Comment by jfResearchEng** [comment]
> I am attempting to build from source (with python3.9) rather than installing the PyPi package. After running `python3 setup.py install` within my conda env, it appears that everything is built correctly and installed, but upon importing into python, I get the following error:
> 
> ```
> Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
> [GCC 7.5.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import labgraph
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/__init__.py", line 56, in <module>
>     from .events import (
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/events/__init__.py", line 17, in <module>
>     from .event_generator import (
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/events/event_generator.py", line 9, in <module>
>     from ..graphs.topic import Topic
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/graphs/__init__.py", line 24, in <module>
>     from .config import Config
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/graphs/config.py", line 8, in <module>
>     from ..messages.message import Field, Message
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/messages/__init__.py", line 18, in <module>
>     from .message import Message, TimestampedMessage
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/messages/message.py", line 15, in <module>
>     from .._cthulhu.bindings import (
>   File "/home/peranpl1/Documents/repos/labgraph/labgraph/_cthulhu/bindings.py", line 24, in <module>
>     import cthulhubindings  # noqa: E402
> ImportError: /home/peranpl1/miniconda/envs/lg-3.9/lib/python3.9/site-packages/cthulhubindings.cpython-39-x86_64-linux-gnu.so: undefined symbol: shm_unlink
> ```
> 
> The Dockerfile you linked is installing from PyPI rather than building from source.
> 
> Thanks for the help!

The reason for this error is that the pybinding is not cross-platform supported. For a quick start of using the LabGraph in Ubuntu, I would recommend using pypi. Alternatively, I will find some time in the future supporting additional linux environments (e.g. via pypi, build from source and conda). If you are interested in getting some hands-on for pybindings, you could use the following docker files as reference in [Centos](https://github.com/facebookresearch/labgraph/blob/main/Dockerfile.Centos) and [Ubuntu](https://github.com/facebookresearch/labgraph/blob/main/Dockerfile.Ubuntu). C++ and python bindings may need to be modified and please be aware that this build from source may not be trivial.

**Comment by pperanich** [comment]
Thanks, I'll take a look at that.

**Comment by cboulay** [comment]
I had a similar error in a different library and this was the most relevant search result.

For me, the problem turned out to be that Cython was finding the `shm_unlink` symbol during linking and at runtime in Ubuntu 22.04, but only during linking (not at runtime) in Ubuntu 20.04. My guess is that a dependency exposes this symbol (transitively) in jammy but not focal.

Anyway, I simply added `"rt"` to my list in `setup(ext_modules=[Extension(..., libraries=[..., "rt"])], ...)` in setup.py and now it works.

If this problem persists in labgraph then this might be a hint. I don't know how Buck works and I couldn't figure out where dependencies are listed so I can't help anymore than that.
