### ISSUE TITLE
Array dimension problem with HDF5 Logger when it is used with np.ndarray

### ISSUE THREAD

**Issue by Yunusbcr** [facebookresearch/labgraph#20]
## 🐛 Bug

HDF5 Logger records only some portion on the numpy array when it has 2 or more dimesion

## To Reproduce

1. Create `RandomMessage.py` as,
```
import labgraph as lg
import numpy as np
# A data type used in streaming, see docs: Messages
class RandomMessage(lg.Message):
    timestamp: float
    data: np.ndarray
```
and save it in same folder with `simple_viz.py`. import in `simple_viz.py` as `from RandomMessage import RandomMessage`. 
!!! If you don't do this, it creates pickle problem.

2. https://github.com/facebookresearch/labgraph/blob/8a02c3dc70251c1036f4c8c759a7e4eb99710316/labgraph/examples/simple_viz.py#L22 change with `NUM_FEATURES = 3` for easy tracking

3. https://github.com/facebookresearch/labgraph/blob/8a02c3dc70251c1036f4c8c759a7e4eb99710316/labgraph/examples/simple_viz.py#L52 add second dimension to the data `timestamp=time.time(), data=np.random.rand(self.config.num_features,2)`

4. https://github.com/facebookresearch/labgraph/blob/8a02c3dc70251c1036f4c8c759a7e4eb99710316/labgraph/examples/simple_viz.py#L91 change to `all_data = np.stack([message.data[:,0] for message in self.state.messages])` for consistency 

5. add logger to `simple_viz.py` as,
```    
# import os 
# from typing import Dict

    def logging(self) -> Dict[str, lg.Topic]:
        return {"AVERAGED_NOISE.GENERATOR.OUTPUT": self.AVERAGED_NOISE.GENERATOR.OUTPUT}


# Entry point: run the Demo graph
if __name__ == "__main__":
    
    options = lg.RunnerOptions(logger_config=lg.LoggerConfig(output_directory=os.getcwd(), recording_name='Data'))                                                                                       
    runner = lg.ParallelRunner(graph=Demo(), options=options)                                
    runner.run()

```
6. Check `Data.h5`
```
import h5py

filename = "Data.h5"
data = h5py.File(filename,'r')

AVERAGED_NOISE_GENERATOR_OUTPUT = data['AVERAGED_NOISE.GENERATOR.OUTPUT']

for message in AVERAGED_NOISE_GENERATOR_OUTPUT:
    print(message) # message[0] for timestamp, message[1] for data  

data.close()
```
output,
```
(1.63596626e+09, array([0.41416002, 0.39325703, 0.66150395]))
(1.63596626e+09, array([0.62143319, 0.41737914, 0.61858237]))
(1.63596626e+09, array([0.44333838, 0.24507895, 0.20770642]))
(1.63596626e+09, array([0.32552889, 0.54726282, 0.05445356]))
(1.63596626e+09, array([0.36576081, 0.38641926, 0.8574152 ]))
(1.63596626e+09, array([0.97234542, 0.00512511, 0.00118584]))
(1.63596626e+09, array([0.11100949, 0.01632484, 0.42616371]))
...
...
```

## Expected behavior

```
(1.63596626e+09, some random numpy array with shape of (3,2))
(1.63596626e+09, some random numpy array with shape of (3,2))
(1.63596626e+09, some random numpy array with shape of (3,2))
(1.63596626e+09, some random numpy array with shape of (3,2))
(1.63596626e+09, some random numpy array with shape of (3,2))
...
...
```

## Environment

```

 - LabGraph Version (e.g., 1.0): 1.0.2 (installed via pip)
 - OS (e.g., Linux/Mac/Windows): Ubuntu 20.04
 - Python version: 3.6.15

**Comment by jfResearchEng** [comment]
Thank you, Yunusbcr to report this issue!

For fix length numpy array, the following could be used in RandomMessage.py:
data: lg.NumpyType((3, 2), np.float64)
instead of -> data: np.ndarray

Logging support for multi-dimensional dynamic array will be added to a to-do list.

I'm going to close this issue for now and feel free to reopen this issue if there's more question(s).
