### ISSUE TITLE
Apache Ant causes 404 error during docker build

### ISSUE THREAD

**Issue by yahiaali** [facebookresearch/labgraph#3]
## 🐛 Bug

`docker build` fails with an HTTP 404 error when trying to download Apache Ant

## To Reproduce

1. Navigate to the root directory of the `labgraph` repository.
1. Run `docker build .`

## Expected behavior

In the following line, Docker attempts to download Apache Ant 1.10.9 from a link that no longer exists:
https://github.com/facebookresearch/labgraph/blob/e9e98ec120cff24fdd11a3c7f3a3059938bc1ff1/Dockerfile#L13

Instead, we should download Apache Ant 1.10.9 from the archive:
```
RUN wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.zip
```

## Environment
 - LabGraph Version (e.g., 1.0): 1.0.0, commit 97e0f18
 - OS (e.g., Linux/Mac/Windows): Ubuntu 18.04.5 LTS
 - Python version: 3.6

**Comment by jfResearchEng** [comment]
This update shall fix the error message: [link](https://github.com/facebookresearch/labgraph/commit/b905bc0caf9f619bec345987a4e039b616918901). I'm going to close this issue. If you still have questions, feel free to re-open this issue.
