### ISSUE TITLE
python executable not found on windows

### ISSUE THREAD

**Issue by mmmspatz** [facebookresearch/labgraph#31]
On Windows, there is no binary named `python3.exe` or `python36.exe` (only `python.exe`), so this fails to find the executable:
https://github.com/facebookresearch/labgraph/blob/4df7f1f379411e5078de343bf0a7b1a34b1573b4/third-party/python/DEFS#L21-L27

`python` used to be in this list, but it was removed in eda02c8429f30f64fb3cf4430841bb5b60dddca3. Can it be added back? The correct python version (3.6 or 3.8, never 2.x) should still be found by line 24.

**Comment by jfResearchEng** [comment]
This is mainly for the case when "python" is reserved for another version. A fix for this would be to copy the python.exe binary to python3.exe or python3.x.exe in the same folder. 
Let me incorporate the logic "python" as well based on your suggestion.
If you encounter other problems, feel free to let us know.

**Comment by jfResearchEng** [comment]
An update can be found here: https://github.com/facebookresearch/labgraph/pull/32

**Comment by jfResearchEng** [comment]
Closing this for now, feel free to reopen if you have more feedback.
