### ISSUE TITLE
LabGraph Monitor Improvement - Add input/output message information in LabGraph Monitor UI

### ISSUE THREAD

**Issue by jfResearchEng** [facebookresearch/labgraph#45]
## 🚀 Feature
Add input/output message information (e.g. data type and message name) in LabGraph Monitor GUI (frontend)

## Additional context

1. Existing application can be found [here] (https://github.com/facebookresearch/labgraph/pull/38)
2. The code should be added at folder is https://github.com/facebookresearch/labgraph/pull/38
3. Create setup.py and README.md, where example can be found [here](https://github.com/facebookresearch/labgraph/tree/main/extensions/labgraph_viz)
4. Add github action support, reference: [here](https://github.com/facebookresearch/labgraph/actions/workflows/main.yml)
5. Add proper license header, [example](https://github.com/facebook/react/blob/main/scripts/babel/transform-object-assign-require.js).

**Comment by fzchriha** [comment]
Can I please work on this issue
