### ISSUE TITLE
Example usage for ZMQ

### ISSUE THREAD

**Issue by patrickmineault** [facebookresearch/labgraph#5]
## 📚 Documentation

Most people using LabGraph will be using external data sources, and thus will likely want to pipe their data through zmq. The examples however, do not use ZMQ. I've assembled a minimalist ZMQ data source and sink example here:

https://github.com/patrickmineault/labgraph/tree/master/labgraph/examples

Do you think that's something that should be in the examples? Let me know and I will assemble an appropriate PR.

**Comment by jfResearchEng** [comment]
Hey patrickmineault,

This is awesome! Feel free to push this as a PR. I'll test and review on my side and get your example published to our community.

Cheers,
Jimmy
