### ISSUE TITLE
LabGraph Monitor Improvement - Support graph attributes in YAML

### ISSUE THREAD

**Issue by jfResearchEng** [facebookresearch/labgraph#53]
Use a similar method in a related [PR](https://github.com/facebookresearch/labgraph/issues/51), to support LabGraph topology in [LabGraph Monitor](https://github.com/facebookresearch/labgraph/tree/main/extensions/prototypes/labgraph_monitor). This will be a function that looks something like:
```def generate_labgraph_monitor(graph: df.Graph) -> None:```
The graph topology itself consists of the following:
* Methods (these are the nodes in the graph)
* Publishers (these are directed edges leaving a method)
* Subscribers (these are directed edges entering a method)
* Nodes (these are logical groupings of methods which always share the same process – technically not part of the topology, but the grouping may be useful to call out)
* Topics
Topics determine what the directed edges are. Any two connected topics will back the same stream. Each stream will have one publisher and one or more subscribers; the edges are all from that publisher to each subscriber.

We can inspect these properties of a graph by looking at these private attributes:
```__topics__```: The topics
```__streams__```: The streams
```__methods__```: The methods (publishers, subscribers, and "transformers" which are just methods with both @publisher and @subscriber decorators)

## Additional context

1. Existing application can be found [here] (https://github.com/facebookresearch/labgraph/tree/main/extensions/graphviz_support)
2. The code should update/replace the following folder: https://github.com/facebookresearch/labgraph/tree/main/extensions/yaml_support
3. Create setup.py and README.md, where example can be found at: https://github.com/facebookresearch/labgraph/tree/main/extensions/labgraph_viz
4. Add github action support, reference: https://github.com/facebookresearch/labgraph/actions/workflows/main.yml
5. Add proper license header, example.

**Comment by bennaaym** [comment]
Hello, @jfResearchEng 
II would like to work on this feature. For this, I would like to know how the "generate_labgraph_monitor" function will be used to support the Front-end of LabGraph Monitor. Are we trying to generate a YAML representation of the graph? (something like: https://github.com/facebookresearch/labgraph/blob/main/extensions/prototypes/labgraph_monitor/examples/mockDataGraph.js)

**Comment by jfResearchEng** [comment]
> Hello, @jfResearchEng I would like to work on this feature. For this, I would like to know how the "generate_labgraph_monitor" function will be used to support the Front-End of LabGraph Monitor. Are we trying to generate a YAML representation of the graph? (something like: https://github.com/facebookresearch/labgraph/blob/main/extensions/prototypes/labgraph_monitor/examples/mockDataGraph.js)

Hello, @bennaaym 

Great to see that you are interested in this feature!

Yes, this is correct. More specifically, LabGraph python application will be a websocket server, LabGraph Monitor (js application) will be a websocket client; websocket clinet applications (e.g. js applications, typescript applications) can connect to the websocket server and receive the YAML graph representation in real time (e.g. every 200 milliseconds).
