### ISSUE TITLE
Determine Source Node in Subscriber?

### ISSUE THREAD

**Issue by dtemir** [facebookresearch/labgraph#68]
## ❓ Questions and Help

I have a publisher.
```python
class NoiseGenerator(lg.Node):
    OUTPUT = lg.Topic(RandomMessage)
    config: NoiseGeneratorConfig

    @lg.publisher(OUTPUT)
    async def generate_noise(self) -> lg.AsyncPublisher:
        while True:
            yield self.OUTPUT, RandomMessage(
                timestamp=time.time(),
                data=np.random.rand(self.config.num_features)
            )
            await asyncio.sleep(1 / self.config.sample_rate)
```

I have a subscriber.

```python
class Serializer(lg.Node):
  INPUT_1 = lg.Topic(RandomMessage)
  config: SerializerConfig
  state: DataState
  
  @lg.subscriber(INPUT_1)
  def add_message_1(self, message: RandomMessage) -> None:
      self.state.data_1 = {
          "timestamp": message.timestamp,
          "numpy": list(message.data),
      }
``` 

They are connected through the graph.

```python
def connections(self) -> lg.Connections:
    return (
        ...
        (self.NOISE_GENERATOR.OUTPUT, self.SERIALIZER.INPUT_1),
        ...
    )
```

**Question: is there a way for me to determine to which publisher my subscriber `INPUT_1` is subscribed to within `def add_message_1()`?**

```python
@lg.subscriber(INPUT_1)
def add_message_1(self, message: RandomMessage) -> None:
    name_of_the_publisher = self.INPUT_1.source_name (should be "NOISE_GENERATOR/OUTPUT")
    self.state.data_1 = {
        "publisher": name_of_the_publisher
        "timestamp": message.timestamp,
        "numpy": list(message.data),
    }
```

**Comment by bennaaym** [comment]
Hey @dtemir, in your example the subscriber is the method **"add_message_1"**, **INPU_1** is a topic to which the method is subscribing, The current implementation of NodeMethod doesn't really hold data about **NOISE_GENERATOR.OUTPUT"** it only holds data related to **INPU_1**

you can check [method.py](https://github.com/facebookresearch/labgraph/blob/main/labgraph/graphs/method.py) to explore the inner implementation of NodeMethods, subscriber and publisher decorators

**Comment by dtemir** [comment]
thank you @bennaaym! i was afraid that would be the case, but i'll try to find another way. i'm trying to do this to be able to associate the input with messages under the [`serializer_node.py`](https://github.com/facebookresearch/labgraph/blob/f9af520095e018b94023eb4450a4efeee5ea5b72/extensions/yaml_support/labgraph_monitor/server/serializer_node.py#L80)

**Comment by dtemir** [comment]
closing this. @jfResearchEng's idea to use graph topology worked well. you can find the solution here: https://github.com/facebookresearch/labgraph/blob/ff2b8ec0107dfc8157480b0d97ca1c2593bede95/extensions/yaml_support/labgraph_monitor/generate_lg_monitor/generate_lg_monitor.py#L186

thank you for your help @bennaaym
